blank_issues_enabled: false
contact_links:
  - name: 📧 Professional Inquiries
    url: mailto:bsmorris1@gmail.com
    about: For job opportunities or professional questions about this infrastructure showcase
  - name: 💼 LinkedIn Profile
    url: https://www.linkedin.com/in/brandonmorriseng
    about: Connect with me on LinkedIn for professional networking
